name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  buildTest:
    name: Build & Test JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          submodules: true
      - name: prepare
        run: brew install exiftool imagemagick
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test
      - name: Test jitpack publish command
        run: ./gradlew :MPChartLib:publishToMavenLocal
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew cAT --continue
          api: 28
          tag: default
          abi: x86_64
          cmdOptions: -noaudio -no-boot-anim -no-window
      - name: Archive Espresso results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: MPChart-Espresso-report
          path: MPChartExample/build/reports/androidTests/connected
          if-no-files-found: error
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: MPChart-Screenshots
          path: |
            MPChartExample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            MPChartExample/build/outputs/androidTest-results/connected
      - name: Compare screenshots
        run: |
          ls -ls MPChartExample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
          cp MPChartExample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected/emulator\(AVD\)\ -\ 9/* screenshotsToCompare
          ./screenShotCompare.sh
      - name: Archive screenshots diffs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: MPChart-Screenshots-diffs
          path: |
            screenshotDiffs

  Check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v3.1.1
        if: ${{ always() }}
        with:
          name: Chart-Lint-report
          path: ./**/build/reports/lint-results*.html
